[package]
name = "spike_iroh_relay"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "spike-iroh"
path = "src/main.rs"

[dependencies]
iroh = { workspace = true }
iroh-relay = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
rand = "0.9"
