[package]
name = "crab_city_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-embed = { version = "8", features = ["interpolate-folder-path", "deterministic-timestamps", "include-exclude"] }
